### PR TITLE
Feature/firebase new tags

### PR DESCRIPTION
**Pull request by jeffreycwitt**

### CODE REVIEW

**Comment by ch-sander** [comment]
A new user left a comment. This user must be approved by a Netlify team owner before comments can be displayed.

[Approve this user](https://app.netlify.com/teams/jeffreycwitt/reviewers)

**Comment by ch-sander** [comment]
A new user left a comment. This user must be approved by a Netlify team owner before comments can be displayed.

[Approve this user](https://app.netlify.com/teams/jeffreycwitt/reviewers)

**Comment by ch-sander** [comment]
Created a new issue [page number #114](https://github.com/lombardpress/lombardpress-webjs/issues/114) in GitHub

**Comment by ch-sander** [comment]
Created a new issue [Structure element label #116](https://github.com/lombardpress/lombardpress-webjs/issues/116) in GitHub

**Comment by ch-sander** [comment]
Created a new issue [line break // word split with angled dash #118](https://github.com/lombardpress/lombardpress-webjs/issues/118) in GitHub

**Comment by ch-sander** [comment]
Created a new issue [image view of § #121](https://github.com/lombardpress/lombardpress-webjs/issues/121) in GitHub

**Comment by jeffreycwitt** [comment]
Created a new issue [Ref Link Does not seem to show in text-view #122](https://github.com/lombardpress/lombardpress-webjs/issues/122) in GitHub

**Pull request merged**
